eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: ${EUREKA_SERVER_ADDRESS:http://localhost:8761/eureka}
      
okta:
  oauth2:
    issuer: https://dev-15585796.okta.com/oauth2/default
    audience: api://default
spring:
  config:
    import: configserver:http://localhost:9296
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    username: local_user
    password: password
  jpa:
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: true
